version: '3'
services:
  tomdunlap-ai:
    container_name: tomdai
    image: tomdunlap-ai:v1
    ports:
      - 8080:8080
      - 8443:8443
      - 50000:50000
      - 127.0.0.1:8001:8001
    volumes:
      - docker_mnt:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 

volumes:
  docker_mnt:
    external: true 
  

